namespace LifxNetPlus {
	/// <summary>
	/// The message type used for LAN communication
	/// </summary>
	public enum MessageType : ushort {
		//Device Messages
		DeviceSetSite = 1,
		DeviceGetService = 2,
		DeviceStateService = 3,
		
		DeviceGetTime = 4,
		DeviceSetTime = 5,
		DeviceStateTime = 6,
		DeviceGetResetSwitch = 7,
		DeviceStateResetSwitch = 8,
		DeviceGetDummyLoad = 9,
		DeviceSetDummyLoad = 10,
		DeviceStateDummyLoad = 11,
		
		DeviceGetHostInfo = 12,
		DeviceStateHostInfo = 13,
		DeviceGetHostFirmware = 14,
		DeviceStateHostFirmware = 15,
		DeviceGetWifiInfo = 16,
		DeviceStateWifiInfo = 17,
		DeviceGetWifiFirmware = 18,
		DeviceStateWifiFirmware = 19,
		DeviceGetPower = 20,
		DeviceSetPower = 21,
		DeviceStatePower = 22,
		DeviceGetLabel = 23,
		DeviceSetLabel = 24,
		DeviceStateLabel = 25,
		DeviceGetTags = 26,
		DeviceSetTags = 27,
		DeviceStateTags = 28,
		DeviceGetTagLabels = 29,
		DeviceSetTagLabels = 30,
		DeviceStateTagLabels = 31,
		DeviceGetVersion = 32,
		DeviceStateVersion = 33,
		DeviceGetInfo = 34,
		DeviceStateInfo = 35,
		DeviceGetMcuRailVoltage = 36,
		DeviceStateMcuRailVoltage = 37,
		DeviceSetReboot = 38,
		DeviceDisableFactoryTestMode = 40,
		DeviceStateFactoryTestMode = 41,
		DeviceStateSite = 42,
		DeviceStateReboot = 43,
		DeviceSetPanGateway = 44,
		DeviceAcknowledgement = 45,
		DeviceSetFactoryReset = 46,
		DeviceStateFactoryReset = 47,
		DeviceGetLocation = 48,
		DeviceSetLocation = 49,
		DeviceStateLocation = 50,
		DeviceGetGroup = 51,
		DeviceSetGroup = 52,
		DeviceStateGroup = 53,
		DeviceGetOwner = 54,
		DeviceSetOwner = 55,
		DeviceStateOwner = 56,
		DeviceEchoRequest = 58,
		DeviceEchoResponse = 59,
		DeviceGetOnboardingFeedback = 96,
		DeviceSetOnboardingFeedback = 97,
		DeviceClearOnboardingFeedback = 98,
		//Light messages
		LightGet = 101,
		LightSetColor = 102,
		LightSetWaveform = 103,
		SetLightBrightness = 104,
		LightSetDimRelative = 105,
		LightSetRgbw = 106,
		LightState = 107,
		LightGetRailVoltage = 108,
		LightSetRailVoltage = 109,
		LightGetTemperature = 110,
		LightStateTemperature = 111,
		LightGetPower = 116,
		LightSetPower = 117,
		LightStatePower = 118,
		LightSetWaveformOptional = 119,
		
		//Infrared
		LightGetInfrared = 120,
		LightStateInfrared = 121,
		LightSetInfrared = 122,
		LightGetLightRestore = 129,
		LightSetLightRestore = 130,
		LightStateLightRestore = 131,
		LightSetSmooth = 141,
		LightGetHevCycle = 142,
		LightSetHevCycle = 143,
		LightStateHevCycle = 144,
		LightGetHevCycleConfiguration = 145,
		LightSetHevCycleConfiguration = 146,
		LightStateHevCycleConfiguration = 147,
		LightGetLastHevCycleResult = 148,
		LightStateLastHevCycleResult = 150,
		
		// WAN
		WanGet = 201,
		WanSet = 202,
		WanState = 203,
		WanGetAuthKey = 204,
		WanSetAuthKey = 205,
		WanStateAuthKey = 206,
		WanSetKeepAlive = 207,
		WanStateKeepAlive = 208,
		WanSetHost = 209,
		WanGetHost = 210,
		WanStateHost = 211,
		WanGetCloud = 212,
		WanSetCloud = 213,
		WanStateCloud = 214,
		
		// DevState?
		DeviceStateUnhandled = 223,
		DeviceGetGrouping = 224,
		DeviceSetGrouping = 225,
		DeviceStateGrouping = 226,
		
		//Wifi
		WifiGet = 301,
		WifiSet = 302,
		WifiState = 303,
		WifiGetAccessPoints = 304,
		WifiSetAccessPoints = 305,
		WifiStateAccessPoints = 306,
		WifiGetAccessPoint = 307,
		WifiStateAccessPoint = 308,
		WifiSetAccessPointBroadcast = 309,
		
		//Sensor
		SensorGetAmbientLight = 401,
		SensorStateAmbientLight = 402,
		SensorGetDimmerVoltage = 403,
		SensorStateDimmerVoltage = 404,
		SensorGetPowerInstantaneous = 405,
		SensorStatePowerInstantaneous = 406,
		
		//Multi zone
		SetColorZones = 501,
		GetColorZones = 502,
		StateZone = 503,
		StateMultiZone = 506,
		MultiZoneGetEffect = 507,
		MultiZoneSetEffect = 508,
		MultizoneStateEffect = 509,
		SetExtendedColorZones = 510,
		GetExtendedColorZones = 511,
		StateExtendedColorZones = 512,

		//Boo, homekit
		HomekitGetPairingCode = 601,
		HomekitStatePairingCode = 602,
		HomekitGetPairingStatus = 603,
		HomekitStatePairingStatus = 604,
		
		//Tile
		GetDeviceChain = 701,
		StateDeviceChain = 702,
		SetUserPosition = 703,
		GetTileState1 = 704,
		GetTileState4 = 705,
		GetTileState16 = 706,
		GetTileState64 = 707,
		StateTileState1 = 708,
		StateTileState4 = 709,
		StateTileState16 = 710,
		StateTileState64 = 711,
		SetTileState1 = 712,
		SetTileState4 = 713,
		SetTileState16 = 714,
		SetTileState64 = 715,
		TileCopyFrameBuffer = 716,
		TileFillFrameBuffer = 717,
		TileGetEffect = 718,
		tileSetEffect = 719,
		TileStateEffect = 720,
		GetTileTapConfig = 721,
		SetTileTapConfig = 722,
		StateTileTapConfig = 723,

		//Switch 
		GetRelayMode = 800,
		SetRelayMode = 801,
		StateRelayMode = 802,
		GetAllRelayModes = 803,
		StateAllRelayModes = 804,
		GetRelayLabel = 810,
		SetRelayLabel = 811,
		StateRelayLabel = 812,
		GetRelayGroup = 813,
		SetRelayGroup = 814,
		StateRelayGroup = 815,
		GetRelayPower = 816,
		SetRelayPower = 817,
		StateRelayPower = 818,
		GetRelayLocation = 819,
		SetRelayLocation = 820,
		StateRelayLocation = 821,
		GetRelay = 822,
		StateRelay = 823,
		GetButtonCount = 901,
		StateButtonCount = 902
	}
}